# Generated by Django 2.0.3 on 2018-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='add_cart',
            field=models.BooleanField(default=False),
        ),
    ]
