# Generated by Django 2.0.3 on 2018-03-28 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180325_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='prod',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod',
            name='slug',
            field=models.SlugField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='p_logo',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterIndexTogether(
            name='prod',
            index_together={('id', 'slug')},
        ),
    ]
