# Generated by Django 2.0.3 on 2018-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180328_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='slug',
            field=models.SlugField(default='2', max_length=200),
        ),
    ]
