# Generated by Django 2.0.3 on 2018-03-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180328_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='prod',
            index_together=set(),
        ),
    ]
