# Generated by Django 2.0.3 on 2018-03-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180329_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='created',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='updated',
        ),
    ]
