# Generated by Django 2.0.3 on 2018-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180329_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='add_cart',
        ),
        migrations.AddField(
            model_name='prod',
            name='quant',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
