# Generated by Django 2.0.3 on 2018-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180402_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='quant',
            field=models.CharField(max_length=250),
        ),
    ]
